name: gh-pages deploy

on:
  push:
    branches:
      - main

jobs:
  commit_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Git Config
      run: |
        git config --global user.name "Carlos Marques"
        git config --global user.email "carlosxjm@gmail.com"

    - name: Commit and Push
      run: |
        git add .
        git commit -m "Test"
        git push origin test
