name: gh-pages deploy

on:
  push:
    branches:
      - main

jobs:
  commit_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Git Config
      run: |
        git config --global user.name "Carlos Marques"
        git config --global user.email "carlosxjm@gmail.com"

    - name: Commit and Push
      run: |
        echo "test" >> README.md
        git add .
        git commit -m "Test"
        git push origin test

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_prefix: "[AUTO-COMMIT] foo/bar replace"
        target_branch: "test"
